[colors.primary]
background = "
foreground = "
dim_foreground = "
bright_foreground = "

[colors.cursor]
text = "
cursor = "

[colors.vi_mode_cursor]
text = "
cursor = "

[colors.search.matches]
foreground = "
background = "

[colors.search.focused_match]
foreground = "
background = "

[colors.footer_bar]
foreground = "
background = "

[colors.hints.start]
foreground = "
background = "

[colors.hints.end]
foreground = "
background = "

[colors.selection]
text = "
background = "

[colors.normal]
black = "
red = "
green = "
yellow = "
blue = "
magenta = "
cyan = "
white = "

[colors.bright]
black = "
red = "
green = "
yellow = "
blue = "
magenta = "
cyan = "
white = "

[colors.dim]
black = "
red = "
green = "
yellow = "
blue = "
magenta = "
cyan = "
white = "

[[colors.indexed_colors]]
index = 16
color = "

[[colors.indexed_colors]]
index = 17
color = "
